name: Python_docker_flask_mediapipe

on:
  push:
    branches:
      - developer
  pull_request:
    branches:
      - main

jobs:
  test_python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Display Python version
        run: |
          python --version
          pip --version
      
      - name: Echo the current date and time
        run: |
          echo "The current date and time is $(date)."
          echo "initial test successful"
          # echo list of all job done
          echo "List of all jobs done"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build
          pip install setuptools wheel twine

      - name: Display Python version
        run: |
          python --version
          pip --version
      # - name: buld package
      #   run: |
      #     python -m build
      - name: Build Wheel
        run: python setup.py sdist bdist_wheel

      - name: Store Wheel on GitHub
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist
      - name: Publish package
        run: echo "Not publishing package"
